In [23]:
import pandas as pd
import numpy as np
from pathlib import Path

# Find project root safely
current_path = Path.cwd()

if current_path.name == "notebooks":
    project_root = current_path.parent
else:
    project_root = current_path

data_path = project_root / "data" / "processed.cleveland.data"

column_names = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "target"
]

df = pd.read_csv(
    data_path,
    names=column_names,
    na_values="?"
)

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

## Run Basic Dataset Checks

In [24]:
# Check number of rows and columns
df.shape

(303, 14)

In [26]:
# Check column names, data types, and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
 13  target    303 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 33.3 KB

In [27]:
# Basic statistics
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000,301.000000,303.000000
mean,54.438944,0.679868,3.158416,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241,4.734219,0.937294
std,9.038662,0.467299,0.960126,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438,1.939706,1.228536
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
50%,56.000000,1.000000,3.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000,3.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000,7.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000,4.000000

In [28]:
# Check missing values
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
target      0
dtype: int64

In [29]:
# Check target values
df["target"].value_counts()

target
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

In [30]:
csv_path = project_root / "data" / "heart.csv"

df.to_csv(csv_path, index=False)

print("Dataset saved to:", csv_path)

Dataset saved to: d:\Projects\heart-disease-risk-prediction\data\heart.csv

# Step 5: Understand and Clean the Dataset

In this step, we will:

1. Check missing values
2. Check duplicate rows
3. Convert target into binary form
4. Save cleaned dataset

This project is using the ML concepts you studied, especially classification, skewed data, decision trees, and XGBoost.

#### 1. Check Missing Values

In [31]:
# Check missing values in each column
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
target      0
dtype: int64

#### 2. Check Duplicate Rows

In [32]:
# Check duplicate rows
df.duplicated().sum()

0

#### 3. Handle Missing Values

In [33]:
# Remove rows with missing values
df = df.dropna()

# Check again
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [34]:
df.shape

(297, 14)

#### 4. Convert Target into Binary Classification

In [35]:
# Convert target into binary classification
df["target"] = df["target"].apply(lambda x: 0 if x == 0 else 1)

# Check new target values
df["target"].value_counts()

target
0    160
1    137
Name: count, dtype: int64

#### 5. Check Data Types

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 297 entries, 0 to 301
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       297 non-null    float64
 1   sex       297 non-null    float64
 2   cp        297 non-null    float64
 3   trestbps  297 non-null    float64
 4   chol      297 non-null    float64
 5   fbs       297 non-null    float64
 6   restecg   297 non-null    float64
 7   thalach   297 non-null    float64
 8   exang     297 non-null    float64
 9   oldpeak   297 non-null    float64
 10  slope     297 non-null    float64
 11  ca        297 non-null    float64
 12  thal      297 non-null    float64
 13  target    297 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 34.8 KB

In [37]:
int_columns = [
    "age", "sex", "cp", "trestbps", "chol", "fbs",
    "restecg", "thalach", "exang", "slope", "ca", "thal", "target"
]

df[int_columns] = df[int_columns].astype(int)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 297 entries, 0 to 301
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       297 non-null    int32
 1   sex       297 non-null    int32
 2   cp        297 non-null    int32
 3   trestbps  297 non-null    int32
 4   chol      297 non-null    int32
 5   fbs       297 non-null    int32
 6   restecg   297 non-null    int32
 7   thalach   297 non-null    int32
 8   exang     297 non-null    int32
 9   oldpeak   297 non-null    float64
 10  slope     297 non-null    int32
 11  ca        297 non-null    int32
 12  thal      297 non-null    int32
 13  target    297 non-null    int32
dtypes: float64(1), int32(13)
memory usage: 19.7 KB

#### 6. Save the Cleaned Dataset

In [39]:
cleaned_path = project_root / "data" / "heart_cleaned.csv"

df.to_csv(cleaned_path, index=False)

print("Cleaned dataset saved to:", cleaned_path)

Cleaned dataset saved to: d:\Projects\heart-disease-risk-prediction\data\heart_cleaned.csv

#### Complete Code for Step 5

In [40]:
# Step 5: Data Cleaning

# 1. Check missing values
print("Missing values before cleaning:")
print(df.isnull().sum())

# 2. Check duplicates
print("\nDuplicate rows:")
print(df.duplicated().sum())

# 3. Remove duplicates
df = df.drop_duplicates()

# 4. Remove missing values
df = df.dropna()

# 5. Convert target into binary classification
# 0 = no heart disease, 1 = heart disease present
df["target"] = df["target"].apply(lambda x: 0 if x == 0 else 1)

# 6. Convert ca and thal to integer
df["ca"] = df["ca"].astype(int)
df["thal"] = df["thal"].astype(int)

# 7. Check cleaned dataset
print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\nTarget distribution:")
print(df["target"].value_counts())

print("\nCleaned dataset shape:")
print(df.shape)

# 8. Save cleaned dataset
cleaned_path = project_root / "data" / "heart_cleaned.csv"
df.to_csv(cleaned_path, index=False)

print("\nCleaned dataset saved to:", cleaned_path)

Missing values before cleaning:
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

Duplicate rows:
0

Missing values after cleaning:
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

Target distribution:
target
0    160
1    137
Name: count, dtype: int64

Cleaned dataset shape:
(297, 14)

Cleaned dataset saved to: d:\Projects\heart-disease-risk-prediction\data\heart_cleaned.csv